import LocalizedStrings from 'localized-strings'

export default new LocalizedStrings.default({
    en: {
        ACCOUNT_VALIDATION_SUBJECT: 'Account Validation',
        HELLO: 'Hello ',
        ACCOUNT_VALIDATION_LINK: 'Please activate your account by clicking the link:',
        REGARDS: 'Kind regards,<br>Wexstream team',
        ACCOUNT_VALIDATION_TECHNICAL_ISSUE: 'Technical Issue! Please click on resend to validate your email.',
        ACCOUNT_VALIDATION_EMAIL_SENT_PART_1: 'A validation email has been sent to ',
        ACCOUNT_VALIDATION_EMAIL_SENT_PART_2: ". It will be expire after one day. If you didn't receive validation email click on resend.",
        ACCOUNT_VALIDATION_LINK_EXPIRED: 'Your validation link may have expired. Please click on resend to validate your email.',
        ACCOUNT_VALIDATION_LINK_ERROR: 'We were unable to find a user for this verification. Please Sign up.',
        ACCOUNT_VALIDATION_SUCCESS: 'Your account was successfully verified.',
        ACCOUNT_VALIDATION_RESEND_ERROR: 'We were unable to find a user with that email. Make sure your Email is correct.',
        ACCOUNT_VALIDATION_ACCOUNT_VERIFIED: 'This account has already been verified. Please sign in.',
        DB_ERROR: 'Database Failure: ',
        IO_ERROR: 'I/O Failure: ',
        DB_DELETE_ERROR: 'Failed to delete from database: ',
        MESSAGE_SUBJECT: 'New Message',
        MESSAGE_BODY: 'sent you the following message:',
        MESSAGE_SUBJECT_TITLE: 'Subject: ',
        MESSAGE_BODY_TITLE: 'Message:',
        SMTP_ERROR: 'Failed to send email: ',
        MESSAGE_LINK: 'View this message on Wexstream.',
        NOTIFICATION_SUBJECT: 'New Notification',
        NOTIFICATION_BODY: 'You have a new notification:',
        GENERIC_ERROR: 'Error: ',
        REQUESTING_USER: 'Requesting user: ',
        NOTIFICATIONS_LINK: 'View your notifications.',
        NOTIFICATION_LINK: 'Notification link.',
        ALREADY_BLOCKED: 'User already blocked.',
        REPORTED: 'reported',
        REPORTED_MESSAGE: 'Reported message: ',
        REPORTED_BY: 'Reported by: ',
        REPORTED_USER: 'Reported user: ',
        CONFERENCE_NOTIFICATION: 'started the live conference',
        CONFERENCE_NOTIFICATION_CLOSED: 'closed the live conference'
    },
    fr: {
        ACCOUNT_VALIDATION_SUBJECT: 'Validation de votre compte',
        HELLO: 'Bonjour ',
        ACCOUNT_VALIDATION_LINK: 'Veuillez activer votre compte en cliquant sur le lien :',
        REGARDS: "Cordialement,<br>L'équipe Wexstream",
        ACCOUNT_VALIDATION_TECHNICAL_ISSUE: 'Problème technique! Veuillez cliquer sur renvoyer pour valider votre e-mail.',
        ACCOUNT_VALIDATION_EMAIL_SENT_PART_1: 'Un email de validation a été envoyé à',
        ACCOUNT_VALIDATION_EMAIL_SENT_PART_2: ". Il expirera au bout d'un jour. Si vous n'avez pas reçu d'e-mail de validation, cliquez sur renvoyer.",
        ACCOUNT_VALIDATION_LINK_EXPIRED: 'Votre lien de validation a peut-être expiré. Veuillez cliquer sur renvoyer pour valider votre e-mail.',
        ACCOUNT_VALIDATION_LINK_ERROR: "Nous n'avons pas pu trouver d'utilisateur correspondant à cette adresse e-mail. Veuillez vous inscrire.",
        ACCOUNT_VALIDATION_SUCCESS: 'Votre compte a été validé avec succès.',
        ACCOUNT_VALIDATION_RESEND_ERROR: "Nous n'avons pas pu trouver d'utilisateur correspondant à cette adresse e-mail. Assurez-vous que votre e-mail est correct.",
        ACCOUNT_VALIDATION_ACCOUNT_VERIFIED: 'Ce compte a déjà été validé. Veuillez vous connecter.',
        DB_ERROR: 'Échec de la requête dans la base de données : ',
        IO_ERROR: "Échec d'E/S : ",
        DB_DELETE_ERROR: 'Échec de la suppression de la base de données : ',
        MESSAGE_SUBJECT: 'Nouveau Message',
        MESSAGE_BODY: 'vous a envoyé le message suivant :',
        MESSAGE_SUBJECT_TITLE: 'Objet : ',
        MESSAGE_BODY_TITLE: 'Message :',
        SMTP_ERROR: "Échec de l'envoi de l'email: ",
        MESSAGE_LINK: 'Consulter ce message sur Wexstream.',
        NOTIFICATION_SUBJECT: 'Nouvelle Notification',
        NOTIFICATION_BODY: 'Vous avez une nouvelle notification : ',
        GENERIC_ERROR: 'Erreur : ',
        REQUESTING_USER: 'Demandeur : ',
        NOTIFICATIONS_LINK: 'Consulter vos notifications.',
        NOTIFICATION_LINK: 'Lien de la notification.',
        ALREADY_BLOCKED: 'Utilisateur déjà bloqué.',
        REPORTED: 'a signalé',
        REPORTED_MESSAGE: 'Message signalé: ',
        REPORTED_BY: 'Siganlé par : ',
        REPORTED_USER: 'Utilisateur signalé : ',
        CONFERENCE_NOTIFICATION: 'a démarré la conférence',
        CONFERENCE_NOTIFICATION_CLOSED: 'a terminé la conférence'
    }
})